# Generated by Django 3.2.3 on 2024-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'ordering': ('date',), 'verbose_name': 'Курс валюты', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='charcode',
            field=models.CharField(max_length=3, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс'),
        ),
    ]
